version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  zoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    ports:
      - "9000:9000"
    environment:
      HTTP_PORT: 9000
      AUTO_CONNECT_CONNECTION_STRING: "zookeeper:2181"
      ZK_CLIENT_TIMEOUT_MILLIS: 5000
      ZK_CONNECT_TIMEOUT_MILLIS: 5000
      ZK_SASL_CLIENT: 'false'
      ZK_HOSTS: "zookeeper:2181"  
    depends_on:
      - zookeeper

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092,kafka2:29093,kafka3:29094
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
      DYNAMIC_CONFIG_ENABLED: true # not necessary for sasl auth, added for tests
    links:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: 'SASL_PLAINTEXT://kafka1:29092,CONTROLLER://kafka1:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'SASL_PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:SASL_PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_SASL_ENABLED: false
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_broker_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SUPER_USERS: "User:admin"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_broker_jaas.conf:/etc/kafka/kafka_broker_jaas.conf
    links:
      - zookeeper
    depends_on:
      - zookeeper

  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9093:9093"
      - "1100:1100"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: 'SASL_PLAINTEXT://kafka2:29093,CONTROLLER://kafka2:29094,PLAINTEXT_HOST://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'SASL_PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://localhost:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:SASL_PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_SASL_ENABLED: false
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_broker_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SUPER_USERS: "User:admin"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1100"
      JMX_PORT: 1100
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_broker_jaas.conf:/etc/kafka/kafka_broker_jaas.conf
    links:
      - zookeeper
    depends_on:
      - zookeeper

  kafka3:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
      - "1101:1101"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: 'SASL_PLAINTEXT://kafka3:29094,CONTROLLER://kafka3:29095,PLAINTEXT_HOST://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'SASL_PLAINTEXT://kafka3:29094,PLAINTEXT_HOST://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:SASL_PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_SASL_ENABLED: false
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_broker_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SUPER_USERS: "User:admin"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1101"
      JMX_PORT: 1101
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_broker_jaas.conf:/etc/kafka/kafka_broker_jaas.conf
    links:
      - zookeeper
    depends_on:
      - zookeeper